# render.yaml - Blueprint para deploy do n8n no Render.com

services:
  # Serviço principal do n8n
  - name: n8n
    type: web         # É um serviço web, acessível pela internet
    env: docker       # Vamos usar a imagem Docker oficial do n8n
    plan: starter     # 'starter' é elegível para o plano gratuito. Mude para um plano pago para produção.
    
    # Define um disco persistente para salvar seus workflows e credenciais
    # Isso é CRUCIAL! Sem isso, você perde tudo a cada deploy.
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n # O diretório onde o n8n salva os dados
      sizeGB: 1       # 1 GB é suficiente para começar

    # Verificação de saúde para o Render saber se o n8n está funcionando
    healthCheck:
      path: /healthz
      
    # Variáveis de ambiente para configurar o n8n
    envVars:
      # Render vai fornecer a URL automaticamente para esta variável
      - key: WEBHOOK_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_URL_WITHOUT_SCHEME}

      # Fuso horário para agendamentos (triggers) funcionarem corretamente
      - key: TZ
        value: America/Sao_Paulo # Ajuste para o seu fuso horário

      # --- Configuração do Banco de Dados ---
      # Diz ao n8n para usar um banco de dados PostgreSQL
      - key: DB_TYPE
        value: postgresdb

      # As variáveis abaixo pegam os dados de conexão diretamente do
      # serviço de banco de dados que definimos mais abaixo. É mágico!
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db # O nome do nosso serviço de DB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

# Serviço de Banco de Dados PostgreSQL Gerenciado
databases:
  - name: n8n-db
    plan: free        # O plano gratuito de DB é ótimo para começar
    databaseName: n8n # O nome do banco de dados
    user: n8n         # O nome do usuário